### ISSUE TITLE
reproduce the performance 

### ISSUE THREAD

**Issue by tangbohu** [jahongir7174/EfficientNetV2#1]
Thanks for the code. Could this repo reproduce the performance on ImageNet as reported in the paper?

**Comment by jahongir7174** [comment]
thank you,
I have not trained the model yet
after training the model, I will update the repo and notice the results in the readme

**Comment by tangbohu** [comment]
Thanks for your quick reply!  It seems that the training code of EfficientNet and EfficientNetV2 on github is quite rare.

**Comment by vkmavani** [comment]
One question, did you use progressive learning?

**Comment by jahongir7174** [comment]
it is not implemented yet, current training strategy is the same as EfficientNetV1

**Comment by tangbohu** [comment]
@jahongir7174 Have you reimplemented EfficientNetV1? I find it is quiet diffcult to reproduce the performance of EfficientNetV1 on ImageNet also. If possible, could you share the code?

**Comment by jahongir7174** [comment]
yes, I have uploaded it to GitHub, you can refer to [this](https://github.com/jahongir7174/EfficientNet-pt)

**Comment by jahongir7174** [comment]
I have updated the repo with the trained weights
