### ISSUE TITLE
Possibility of forking and add arguments

### ISSUE THREAD

**Issue by AnhMinhTran** [jahongir7174/EfficientNetV2#3]
Hi, thanks for your wonderful code, may I ask if I can have your permission to fork you code and add arguments for your training, that would improve on how easy it is to use the script?

A few additional questions?

- Do I have to specify number of classes I need to train
- Have you compared your result with timm library yet?

**Comment by jahongir7174** [comment]
Hello,
1. You can fork and use it for your purpose
2. It is designed for IMAGENET so you can change the number of classes in [this line](https://github.com/jahongir7174/EffcientNetV2/blob/83841154cd493177d4b78bdc9ecddc939235b8e2/nets/nn.py#L138)
3. I did not compare the results yet, I am training the network, it is still ongoing, after training is finished, I will upload the model weights trained on IMAGENET
