### ISSUE TITLE
Progressive Learning with adaptive Regularization

### ISSUE THREAD

**Issue by jjb202** [jahongir7174/EfficientNetV2#5]
what part of the code can reflect the Progressive Learning with adaptive Regularization?

**Comment by jahongir7174** [comment]
training strategy is the same as efficientnetv1

**Comment by mahendrathapa** [comment]
@jahongir7174  Any plan to implement this one?

**Comment by jahongir7174** [comment]
it is not on my TODO list for this year

**Comment by jahongir7174** [comment]
@hellogry @mahendrathapa It is implemented in the latest update
