### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by Lqm26** [jahongir7174/EfficientNetV2#7]

**Comment by jahongir7174** [comment]
I can not understand the question clearly. I think you are asking about the dataset that is used for training.
If so, I used ImageNet-1K dataset for training the EfficientNetV2-S model. See [this line](https://github.com/jahongir7174/EfficientNetV2/blob/eb5c6c16603dfdc2fbf5f8e2a8da033a666518a9/main.py#L19) for dataset location in your desktop.
